[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y --no-install-recommends chromium",
    "npm install"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "npm start"

[environment]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
