[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"

[build.environment]
NODE_ENV = "production"

[[build.environment]]
name = "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD"
value = "false"
